version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "clients"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bed7k0wh2a6n"
s3_prefix = "clients"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "HashKeyElementNameId=\"id\" BucketName=\"client-swagger-bucket\" FQDN=\"iotechweek.com.br\" ZoneId=\"Z19I9C90318W7Z\" HashKeyElementCreateDate=\"create_date\" HashKeyElementType=\"S\" ReadCapacityUnits=\"5\" WriteCapacityUnits=\"10\""
